### ISSUE TITLE
Tracker-free version?

### ISSUE THREAD

**Issue by IzzySoft** [kdrag0n/tipatch#1]
That sounds like a great app, congrats! I just hesitate installing it as it comes with several trackers (Crashlytics, Firebase Analytics, Firebase itself). Is it possible to provide a tracker-free version for us "tin foils"? I'd [provide that via my repo](https://apt.izzysoft.de/fdroid/index/apk/com.kdrag0n.tipatch) (which, as requested by a user, currently holds the version you provide in the releases section, thank you for that; my updater script fetches new versions automatically, usually within 24h). I'm thinking along the lines of a `tipatch-app-noanalytics-<version>.apk` :wink:

**Comment by kdrag0n** [comment]
Crashlytics has been extremely helpful for fixing bugs and crashes, so I'm
worried that more people will use the tracker-free version and I won't be
able to fix any bugs they encounter. What do you think about switching to
Sentry, privacy wise?

**Comment by IzzySoft** [comment]
First thank you for your fast response!

You mean [this Sentry](https://sentry.io/welcome/)? Well, better than having the data at Google and the likes, but it's still a hosted service and I don't know where the data is stored (some cloud?) – or would you [host your own instance](https://docs.sentry.io/server/installation/)? But if that would replace Crashlytics and Firebase, and the user can turn it off (better even, it's turned off by default – with optionally the user being asked to turn it on at the first start), IMHO that would be a huge improvement privacy-wise. From a quick skimming, Sentry sounds good.

And yes, if there is a tracker-free version, us tin-foils will prefer using that. Still, at least 90% will pick their version from Playstore (where you most likely will leave the trackers in), while the privacy-aware using the tracker-free version from my repo will, in comparison, be few. You could also use different package names for the two to keep them apart. And as for bugs, you could have an option to export debug information from within the app and give options to save it to SD card as well as "sharing" it to another app to allow for directly mailing it to you. Both options given, users can decide to trust you with "unsanitized" debug information – or first investigate the SD card export. In both cases, as long as you don't use a Gmail address, leaving the "big collectors" out of the equation. Just naming the options :wink:

**Comment by kdrag0n** [comment]
I'll look into making a tracker free version of 1.4 soon. It'll probably
have a way to send simple reports to my ProtonMail. Just not sure how I'll
handle removing the dependencies and GMS plugin for that version.

**Comment by IzzySoft** [comment]
GMS is a problem for the official F-Droid repo. It's not a show-stopper for mine, as compatibility can be gained by using microG. So if you can get rid of that: great, we can go for the official repo then if you like. If you can't: well, then it can remain in my repo :wink:

Looking forward to that v1.4 then. Kudos for accepting the challenge and really doing it, a big :+1: and thanks!

**Comment by kdrag0n** [comment]
Done as a `lite` variant of v1.4. Confirmed to be free of GMS/Crashlytics/Firebase. [Release link](https://github.com/kdrag0n/tipatch/releases/tag/v1.4), [direct APK link](https://github.com/kdrag0n/tipatch/releases/download/v1.4/tipatch-app-lite-v1.4.apk). Enjoy!

**Comment by IzzySoft** [comment]
Thanks a lot!!! :+1: My scanner confirms that as well :smiley:
