### ISSUE TITLE
Push Tipatch-lite to F-Droid

### ISSUE THREAD

**Issue by ghost** [kdrag0n/tipatch#3]
As you already wrote a tracker-free and permission-lite ;) version #1, I think it's time to push that version to [F-Droid](https://gitlab.com/fdroid/rfp). This way privacy minded users have always up to date versions as well and don't have to rely on [private repositories](https://apt.izzysoft.de/fdroid/index.php) (note that this is not the lite version at the time of writing!).

**Comment by kdrag0n** [comment]
Izzy's repo now contains the lite version. I'll look into official F-Droid for v1.5.

**Comment by rarecaller** [comment]
The project seems a bit abandoned, but it is still useful and very appropriate for F-Droid store.

**Comment by kdrag0n** [comment]
Sorry for the inactivity. Tipatch should finally be receiving some updates in a few days as soon as I find some free time for it.

**Comment by IzzySoft** [comment]
We're all waiting for those few days to arrive (no pressure, just a humorful reminder :wink:). It's been a year now since the last update – so we hope nobody is drowning you in other work…

**Comment by IzzySoft** [comment]
@kdrag0n looks you won't find time for this (or will you? :pray:) – but maybe you can answwer a short question: did you configure Sentry.io for opt-in – or in other words, will the user be asked **before** any data is sent? That would then make the `Tracking` anti-feature obsolete.

**Comment by kdrag0n** [comment]
Tipatch is no longer maintained so this will never be done, sorry.

To answer your question: Sentry is not opt-in and there's no way to opt out on , but the lite build:

**Comment by kdrag0n** [comment]
Tipatch is no longer maintained so this will never be done, sorry.

To answer your question: Sentry is not opt-in and there's no way to opt out in standard release builds, but the lite build has the Sentry SDK disabled so no data will be sent:

- https://github.com/kdrag0n/tipatch/blob/android/app/src/lite/res/values/attr.xml#L3
- https://github.com/kdrag0n/tipatch/blob/android/app/src/main/java/com/kdrag0n/tipatch/MainActivity.kt#L75

**Comment by IzzySoft** [comment]
Sad to read it's no longer maintained. But thanks for the details, much appreciated!

Guess this issue can be closed then, the original reporter was ghosted and thus cannot do this anymore…
