### ISSUE TITLE
Empty readme

### ISSUE THREAD

**Issue by beerisgood** [kdrag0n/tipatch#4]
I found your app in F-Droid but after I try to read more about it on the linked homepage (which give a 404) i try to read the GitHub readme which is empty.
So where can we read more about?

**Comment by kdrag0n** [comment]
Fixed. There is now a [README](https://github.com/kdrag0n/tipatch/blob/android/README.md) and a [website](https://khronodragon.com/projects/tipatch/).

**Comment by beerisgood** [comment]
Thanks
